-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:California Institute of Technology 0x1506",
  mode = "1920x1080@59.93",
  position = "10864x1286",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-5",
  mode = "1920x1080@60.00",
  position = "9805x206",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "DP-6",
  mode = "1920x1080@60.00",
  position = "11725x206",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "DP-5", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "DP-5" })
hl.workspace_rule({ workspace = "3", monitor = "DP-5" })
hl.workspace_rule({ workspace = "4", monitor = "desc:California Institute of Technology 0x1506", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:California Institute of Technology 0x1506" })
hl.workspace_rule({ workspace = "6", monitor = "desc:California Institute of Technology 0x1506" })
hl.workspace_rule({ workspace = "7", monitor = "DP-6", default = true, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "DP-6" })
hl.workspace_rule({ workspace = "9", monitor = "DP-6" })
